#
# This file contains configuration flags to customize your site
#

title: Mostafa Samir's Blog

username: Mostafa Samir
user_description: Wandering in a lifelong journey seeking after truth.
user_title: Senior Machine Learning Research Engineer
email: mostafa.3210@gmail.com
twitter_username: M0stafa_Samir
github_username:  Mostafa-Samir
linkedin_username: m0stafasamir
disqus_username: mostafa-samir-blog

# Name of your site (displayed in the header)
name: Mostafa Samir

# Short bio or description (displayed in the header)
description: Wandering in a lifelong journey seeking after truth

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/5209140?v=2&s=460

#
# Flags below are optional
#

# Your disqus shortname, entering this will enable commenting on posts
disqus: mostafa-samir-blog

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-57191995-1



url: "https://mostafa-samir.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

links:
  - title: Home
    url: /
  - title: Categories
    url: /categories
  - title: About Me
    url: /about
  - title: How Machine Learning Works
    url: /how-machine-learning-works

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
